spring:
    profiles:
        active: dev
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: false
    datasource:
        url: jdbc:mysql://den1.mysql3.gear.host:3306/portfysample
        username: portfysample
        password: Fs6s~2cm9j_3